name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  # --- ETAPA DE CI (Integração Contínua) ---
  build-test-scan:
    name: Build, Test and SAST
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout do código [cite: 28]
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante para o SonarCloud analisar o histórico

      # 2. Install (Instalação de dependências) [cite: 29]
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install

      # 3. Testes [cite: 30]
      # Apenas executa; não precisa cobertura alta, mas precisa rodar.
      - name: Run Tests
        run: npm test

      # 4. Ferramenta SAST - SonarCloud [cite: 18, 19]
      # O pipeline não para mesmo com falhas no Sonar [cite: 31, 32]
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token padrão do Github
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Você cria esse secret

  # --- ETAPA DE CD (Entrega Contínua) ---
  deploy:
    needs: build-test-scan # Só roda se o CI passar
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy apenas na main (opcional, mas recomendado)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login no Docker Hub [cite: 37]
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e Push da Imagem Docker [cite: 35, 38]
      # Gera versão baseada no SHA do commit e a tag 'latest'
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nome-do-repo:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nome-do-repo:latest

      # Deploy no Render [cite: 39, 41]
      # Usa o Deploy Hook (Webhook) do Render
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}